import {
  TroiTrongDay,
  TroiTrongNight,
  MayItDay,
  MayItNight,
  MayNhieuDay,
  MayNhieuNight,
  MuaNangDay,
  MuaNangNight,
  MuaDay,
  MuaNight,
  DongDay,
  DongNight,
  SuongDay,
  SuongNight,
  TuyetDay,
  TuyetNight,
} from "./WeatherIcon";
const IconComponents = {
  troiTrongDay: TroiTrongDay,
  troiTrongNight: TroiTrongNight,
  mayItDay: MayItDay,
  mayItNight: MayItNight,
  mayNhieuDay: MayNhieuDay,
  mayNhieuNight: MayNhieuNight,
  muaNangDay: MuaNangDay,
  muaNangNight: MuaNangNight,
  muaDay: MuaDay,
  muaNight: MuaNight,
  dongDay: DongDay,
  dongNight: DongNight,
  suongDay: SuongDay,
  suongNight: SuongNight,
  muaTuyetDay: TuyetDay,
  muaTuyetNight: TuyetNight,
};
export default IconComponents;
